import { Menu } from '@headlessui/react';
import Cookies from 'js-cookie';
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect, useState } from "react";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { Store } from "../utils/Store";
import DropdownLink from './DropdownLink';


export default function Layout({ title, children }) {
  const {status, data:session} = useSession();
  const {state, dispatch} = useContext(Store);
  const {cart} = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a,c) => a + c.quantity, 0));}, [cart.cartItems]);
  
    const logoutClickHandler = () => {
      Cookies.remove('cart');
      dispatch({ type: 'CART_RESET' });
      signOut({ callbackUrl: '/login' });
    };

  return (
    <>
    <Head>

        <title>{title ? title +"-Gorarbd":"Gorarbd"}</title>
        <meta name="description" content="Generated by create next app"/>
        <link href="/favicon.ico" rel="icon"/>


    </Head>
    <ToastContainer position="bottom-center" limit={1}/>
      <div className="flex min-h-screen flex-col justify-between">
      <header>
        <nav className="flex justify-between shadow-slate-200 shadow-lg h-12 px-8 py-2 bg-amber-400">
          <Link href="/">
         
         <p className='text-2xl font-semibold'><span className='text-red-600'>FIXED </span>BD</p>
          </Link>
          <div className="space-x-4">
            <Link href="/cart">Cart
            {cartItemsCount > 0 && (
              <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                {cartItemsCount}
              </span>
            )}
            </Link>
            
              {status === 'loading' ? ('Loading'):
              
                session?.user ? (
                  <Menu as="div" className="relative inline-block">
                  <Menu.Button className="text-blue-600 relative">
                    {session.user.name}
                  </Menu.Button>
                  <Menu.Items className="absolute right-0 w-56 origin-top-right bg-white  shadow-lg ">
                    <Menu.Item>
                      <DropdownLink className="dropdown-link" href="/profile">
                        Profile
                      </DropdownLink>
                    </Menu.Item>
                    <Menu.Item>
                      <DropdownLink
                        className="dropdown-link"
                        href="/order-history"
                      >
                        Order History
                      </DropdownLink>
                    </Menu.Item>
                    {session.user.isAdmin && (
                      <Menu.Item>
                        <DropdownLink
                          className="dropdown-link"
                          href="/admin/dashboard"

                        >
                          <Link href={"./dashboard"}>Admin dashboard</Link>
                        </DropdownLink>
                      </Menu.Item>
                    )}
                    <Menu.Item>
                      <a
                        className="dropdown-link"
                        href="#"
                        onClick={logoutClickHandler}
                      >
                        Logout
                      </a>
                    </Menu.Item>
                  </Menu.Items>
                </Menu>
              ) :
              (
                <Link href="/login">Log In</Link>
              )
            
            }
              
          </div>
        </nav>
      </header>

      <main className="container m-auto px-4 mt-5">{children}</main>

      {/* footer part */}

      


      <footer className="flex h-10 justify-center items-center shadow-inner bg-lime-600">

      
  

        <p>Web Development &copy;Right-2022 </p>
      </footer>

      
      </div>
    </>
  );
}
